GameObject -> BloonScript reference
Serpendio/TotallyOriginalTowerDefense pull request #2
Opened 2023-06-17 20:25 UTC by SSeelos

you can reference monobehaviours instead of gameobjects so you dont have to call get component (wich might not even be on it)

2023-06-17 23:19 UTC, Serpendio commented
What if for this one I wish to also instantiate with the Rigidbody & SpriteRenderer. 
Sure I could AddComponent, but using a prefab is both simpler to quickly modify and programatically faster, no?

2023-06-18 08:58 UTC, SSeelos commented
that should not be a problem. the reference will still point to the prefab where the monobehaviour is added to. so you can just call get component on the component itself just as you would with a gameobject reference
![image](https://github.com/Serpendio/TotallyOriginalTowerDefense/assets/30175883/b741a2ee-caff-4ff1-9aa7-00364fcdb35f)

2023-06-18 11:49 UTC, SSeelos reviewed
my comment

2023-06-18 11:49 UTC, SSeelos commented on Assets/Scripts/BloonSpawner.cs
> +        var script = Instantiate(bloonBase);
my review

2023-06-18 11:51 UTC, SSeelos commented on Assets/ScriptTemplates/81-C# Script__MonoBehaviour-MB.cs.txt
> -    void Awake()
i like having awake int there but i see your point
i use awake to set up dependencies (getcomponent) calls
then in start i might get properties of the cached components

2023-06-18 11:53 UTC, SSeelos commented on Assets/Scripts/BloonSpawner.cs
> +        var script = Instantiate(bloonBase);
my reply

2023-06-18 12:27 UTC, Serpendio requested changes

2023-06-18 12:27 UTC, Serpendio commented on Assets/ScriptTemplates/81-C# Script__ScriptableObject-SO.cs.txt
> +using System.Collections.Generic;
```suggestion
```
No need for these in most ScriptableObjects either

2023-06-18 13:15 UTC, Serpendio approved these changes

2023-06-18 13:16 UTC, merged